"""add description to products

Revision ID: 583be5df8cc3
Revises: 0e4d714e120d
Create Date: 2020-10-08 10:41:27.372959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583be5df8cc3'
down_revision = '0e4d714e120d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'description')
    # ### end Alembic commands ###
